name: CI

on: [push, pull_request]

jobs:
  lint:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.10'
      action: 'lint'

  test:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      python-version: '3.10'
      action: 'test'

  docker-build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # רק אחרי ש- lint ו- test סיימו
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-python-app .
