name: Reusable Quality Check

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      action:
        required: true
        type: string

jobs:
  quality:
    runs-on: ubuntu-latest
    env:  # נוסיף את PYTHONPATH כאן
      PYTHONPATH: ${{ github.workspace }}/src

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        if: ${{ inputs.action == 'lint' }}
        run: flake8 src tests

      - name: Run pytest
        if: ${{ inputs.action == 'test' }}
        run: pytest --maxfail=1 --disable-warnings -q

  docker-build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-python-app .
